[package]
name = "aoc04"
version = "0.1.0"
authors = ["Devin Schulz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
